## PyTorch Basic

https://wikidocs.net/52415

* 2D Tensor : (Batch size, dim), DataFrame
* 3D Tensor : (Batch size, width, height), Computer Vision / (Batch size, length, dim) NLP

#### 다음은 4개의 문장을 4x3 2D 텐서로 변환한 것이다.

[[나는 사과를 좋아해], [나는 바나나를 좋아해], [나는 사과를 싫어해], [나는 바나나를 싫어해]]

-> [['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]

In [1]:
# 각 단어를 다음과 같이 벡터로 변환하였을 때
나는 = [0.1, 0.2, 0.9]
사과를 = [0.3, 0.5, 0.1]
바나나를 = [0.3, 0.5, 0.2]
좋아해 = [0.7, 0.6, 0.5]
싫어해 = [0.5, 0.6, 0.7]

In [2]:
# 각 문장은 다음과 같이 4 x 3 x 3 3D 텐서로 만들 수 있다.
[[나는, 사과를, 좋아해],
 [나는, 바나나를, 좋아해],
 [나는, 사과를, 싫어해],
 [나는, 바나나를, 싫어해]]

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

#### batch size = 2로 만들 경우

In [3]:
# 1번 배치
[[나는, 사과를, 좋아해],
 [나는, 바나나를, 좋아해]]

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]

In [4]:
# 2번 배치
[[나는, 사과를, 싫어해],
 [나는, 바나나를, 싫어해]]

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

### Numpy로 Tensor 만들기

In [5]:
import numpy as np

#### 1D

In [6]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [7]:
print('Rank of t:', t.ndim) # 차원
print('Shape of t:', t.shape) # 크기

Rank of t: 1
Shape of t: (7,)


#### 2D

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


### Pytorch Tensor

In [10]:
import torch

#### 1D Tensor

In [11]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size())# shape

1
torch.Size([7])
torch.Size([7])


In [13]:
# 슬라이싱은 numpy와 동일하다.
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


#### 2D Tensor

In [14]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print(t.dim())
print(t.shape)

2
torch.Size([4, 3])


In [16]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [17]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [18]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [19]:
# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2) # [3] -> [[3, 3]] 으로 연산 됨

tensor([[4., 5.]])


In [20]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # -> [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # -> [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Calculation

#### matmul

In [21]:
# 행렬곱
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1:', m1.shape)
print('Shape of Matrix 2:', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


#### mul

In [22]:
# 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]]) # -> [[1, 1], [2, 2]]
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


#### mean

In [23]:
# 평균
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [24]:
# 2D 평균
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0)) # dim = 0 = 첫 번째 차원(행)을 제거 -> 1 x 2
print(t.mean(dim=1)) # dim = 1 = 두 번째 차원(열)을 제거 -> 2 x 1

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


#### sum

In [25]:
# 덧셈
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### max, argmax

In [26]:
# Max, ArgMax(max index return)
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())

tensor(4.)


In [27]:
# dim 옵션을 주면 argmax도 함께 리턴한다. 첫 번째 열에서 max는 1번째, 두 번째 열에서 max는 1번째 이므로 [1, 1]을 리턴한다.
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [28]:
print('Max:', t.max(dim=0)[0]) # Max
print('Max:', t.max(dim=0)[1]) # Argmax

Max: tensor([3., 4.])
Max: tensor([1, 1])


### Tensor Manipulation

#### View, 원소의 수를 유지하면서 크기를 변경

In [29]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [30]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


* -1은 파이토치가 임의로 차원을 결정하라는 의미

In [31]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### squeeze, 1인 차원을 제거

In [32]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [33]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### unsqueeze, 1인 차원을 추가

In [34]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [35]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [36]:
print(ft.view(1, -1)) # view로도 unsqueeze를 구현 가능
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [38]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### Type Casting

In [39]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [40]:
print(lt.float()) # 타입 변환

tensor([1., 2., 3., 4.])


In [41]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [42]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


#### Concatenate

In [43]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7 ,8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=0).shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])


In [44]:
print(torch.cat([x, y], dim=1))
print(torch.cat([x, y], dim=1).shape)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


#### Stacking

In [45]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [46]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [47]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [48]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### ones_like, zeros_like

In [49]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [50]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [51]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### In-place Operation, 덮어쓰기 연산

In [52]:
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [53]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Python Class

In [54]:
class Calculator:
    def __init__(self): # 생성자. 초기화 함수
        self.result = 0

    def add(self, num):
        self.result += num
        return self.result

In [55]:
cal1 = Calculator()
cal2 = Calculator()

print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
