In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

### Linear Regression

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


#### 가중치

In [6]:
W = torch.zeros(1, requires_grad=True) # 값이 변동되도록 하려면 True
print(W)

tensor([0.], requires_grad=True)


#### 편향

In [7]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


#### 가설

In [8]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


#### 비용 함수

In [9]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


#### 경사 하강법

In [10]:
optimizer = optim.SGD([W, b], lr=0.01)

In [11]:
optimizer.zero_grad() # gradient를 0으로 초기화
cost.backward() # 비용 함수를 미분하여 gradient 계산
optimizer.step() # W, b 업데이트

####  정리

In [12]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999
for epoch in range(nb_epochs + 1):
    
    # H(x)
    hypothesis = x_train * W + b
    
    # cost
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    # optim
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

#### optimizer.zero_grad()

In [13]:
# zero_grad()를 통해 초기화해주지 않으면 계속해서 값이 누적된다.
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    z = 2*w
    
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


#### torch.manual_seed()

In [14]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [15]:
torch.manual_seed(1)
print('랜덤 시드가 1일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 1일 때
tensor([0.7576])
tensor([0.2793])


In [16]:
torch.manual_seed(3)
print('랜덤 시드가 다시 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 다시 3일 때
tensor([0.0043])
tensor([0.1056])


### Autograd

In [17]:
w = torch.tensor(2.0, requires_grad=True)

In [18]:
z = 2 * w**2 + 5

In [19]:
z.backward()

In [20]:
# z를 w로 미분한 값이 저장됨
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


### Multivariable Linear regression

In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [22]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [23]:
w1 = torch.zeros(1, requires_grad=True) # = torch.Tensor(0., requires_grad=True) = 
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [24]:
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
    
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079378


#### 행렬 연산(내적, dot)을 고려하여 구현

In [25]:
x_train  =  torch.FloatTensor([[73,  80,  75], # x1_train, x2_train, x3_train
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [26]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [27]:
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [28]:
hypothesis = x_train.matmul(W) + b

In [29]:
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7861,  95.8280]) Cost: 3069.590820
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

### nn.Module로 선형회귀 구현

In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [31]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [32]:
# 모델 선언 및 초기화. (input_dim, output_dim)
model = nn.Linear(1, 1)

In [33]:
print(list(model.parameters())) # 모델이 W, b를 임의로 초기화했다.

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [34]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [35]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [36]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var) # forward 연산이라고 한다.
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) # 정답은 8이며, 8에 가까운 값을 출력한다.

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [37]:
print(list(model.parameters())) # model의 최종 파라미터

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


#### 다중 선형 회귀 구현

In [38]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [39]:
model = nn.Linear(3,1) # 입력 차원 = 3, 출력 차원 = 1

In [40]:
print(list(model.parameters())) # 임의로 초기화된 W, b

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [41]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [42]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960053
Epoch  200/2000 Cost: 5.654707
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091429
Epoch  500/2000 Cost: 4.831834
Epoch  600/2000 Cost: 4.585997
Epoch  700/2000 Cost: 4.353075
Epoch  800/2000 Cost: 4.132411
Epoch  900/2000 Cost: 3.923455
Epoch 1000/2000 Cost: 3.725502
Epoch 1100/2000 Cost: 3.537972
Epoch 1200/2000 Cost: 3.360326
Epoch 1300/2000 Cost: 3.192056
Epoch 1400/2000 Cost: 3.032674
Epoch 1500/2000 Cost: 2.881700
Epoch 1600/2000 Cost: 2.738672
Epoch 1700/2000 Cost: 2.603201
Epoch 1800/2000 Cost: 2.474846
Epoch 1900/2000 Cost: 2.353286
Epoch 2000/2000 Cost: 2.238110


In [43]:
new_var =  torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) # 훈련 때 사용한 값으로, 실제 y는 152

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.7184]], grad_fn=<AddmmBackward0>)


In [44]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8541, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


### Class로 구현

#### Linear Regression

In [45]:
# model = nn.Linear(1, 1)
class LinearRegressionModel(nn.Module):
    def __init__(self): #
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

#### 다중 선형 회귀

In [46]:
# model = nn.Linear(3, 1)
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [47]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [48]:
model = LinearRegressionModel()

In [49]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [50]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 18.474602
Epoch  100/2000 Cost: 0.136136
Epoch  200/2000 Cost: 0.084124
Epoch  300/2000 Cost: 0.051984
Epoch  400/2000 Cost: 0.032123
Epoch  500/2000 Cost: 0.019850
Epoch  600/2000 Cost: 0.012266
Epoch  700/2000 Cost: 0.007580
Epoch  800/2000 Cost: 0.004684
Epoch  900/2000 Cost: 0.002894
Epoch 1000/2000 Cost: 0.001788
Epoch 1100/2000 Cost: 0.001105
Epoch 1200/2000 Cost: 0.000683
Epoch 1300/2000 Cost: 0.000422
Epoch 1400/2000 Cost: 0.000261
Epoch 1500/2000 Cost: 0.000161
Epoch 1600/2000 Cost: 0.000100
Epoch 1700/2000 Cost: 0.000062
Epoch 1800/2000 Cost: 0.000038
Epoch 1900/2000 Cost: 0.000023
Epoch 2000/2000 Cost: 0.000015


In [51]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [52]:
model = MultivariateLinearRegressionModel()

In [53]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [54]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 24821.373047
Epoch  100/2000 Cost: 0.849148
Epoch  200/2000 Cost: 0.825597
Epoch  300/2000 Cost: 0.803225
Epoch  400/2000 Cost: 0.781968
Epoch  500/2000 Cost: 0.761779
Epoch  600/2000 Cost: 0.742587
Epoch  700/2000 Cost: 0.724357
Epoch  800/2000 Cost: 0.707025
Epoch  900/2000 Cost: 0.690548
Epoch 1000/2000 Cost: 0.674883
Epoch 1100/2000 Cost: 0.659985
Epoch 1200/2000 Cost: 0.645810
Epoch 1300/2000 Cost: 0.632342
Epoch 1400/2000 Cost: 0.619514
Epoch 1500/2000 Cost: 0.607307
Epoch 1600/2000 Cost: 0.595689
Epoch 1700/2000 Cost: 0.584615
Epoch 1800/2000 Cost: 0.574086
Epoch 1900/2000 Cost: 0.564045
Epoch 2000/2000 Cost: 0.554474


### 미니 배치 & 배치 크기

#### 미니배치

In [55]:
# epoch는 전체 훈련 데이터가 한 번 사용된 주기
# 배치는 전체 데이터를 배치 크기만큼 나누어 학습을 진행. 1 epoch에서 미니 배치 수만큼 학습을 진행한다.

# 배치는 2배수를 활용한다. CPU/GPU의 메모리가 2배수이므로 효율이 더 좋다고 알려져 있기 때문.

#### 이터레이션

In [56]:
# 1 epoch에서 학습이 진행된 횟수를 이터레이션이라고 한다.
# = 미니 배치 수

In [57]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [58]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [59]:
dataset = TensorDataset(x_train, y_train)

In [60]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True) # shuffle은 한 epoch마다 데이터를 섞어준다.

In [61]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [62]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples

        prediction = model(x_train)

        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()))

Epoch    0/20 Batch 1/3 Cost: 32868.546875
Epoch    0/20 Batch 2/3 Cost: 8253.976562
Epoch    0/20 Batch 3/3 Cost: 3580.594238
Epoch    1/20 Batch 1/3 Cost: 670.870789
Epoch    1/20 Batch 2/3 Cost: 462.119263
Epoch    1/20 Batch 3/3 Cost: 113.443825
Epoch    2/20 Batch 1/3 Cost: 18.598494
Epoch    2/20 Batch 2/3 Cost: 9.061541
Epoch    2/20 Batch 3/3 Cost: 4.041673
Epoch    3/20 Batch 1/3 Cost: 0.020788
Epoch    3/20 Batch 2/3 Cost: 0.833903
Epoch    3/20 Batch 3/3 Cost: 0.693444
Epoch    4/20 Batch 1/3 Cost: 0.163755
Epoch    4/20 Batch 2/3 Cost: 0.754121
Epoch    4/20 Batch 3/3 Cost: 0.297472
Epoch    5/20 Batch 1/3 Cost: 0.393005
Epoch    5/20 Batch 2/3 Cost: 0.134999
Epoch    5/20 Batch 3/3 Cost: 0.505432
Epoch    6/20 Batch 1/3 Cost: 0.402871
Epoch    6/20 Batch 2/3 Cost: 0.228513
Epoch    6/20 Batch 3/3 Cost: 0.402366
Epoch    7/20 Batch 1/3 Cost: 0.409400
Epoch    7/20 Batch 2/3 Cost: 0.237290
Epoch    7/20 Batch 3/3 Cost: 0.213745
Epoch    8/20 Batch 1/3 Cost: 0.264171
Epoch   

In [63]:
new_var =  torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.5295]], grad_fn=<AddmmBackward0>)


#### Custom Dataset

In [64]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [65]:
# Dataset 상속
class CustomDataset(Dataset): 
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]

    # 총 데이터의 개수를 리턴
    def __len__(self): 
        return len(self.x_data)

    # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
    def __getitem__(self, idx): 
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [66]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [67]:
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [68]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):

        x_train, y_train = samples

        prediction = model(x_train)

        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()))

Epoch    0/20 Batch 1/3 Cost: 10398.765625
Epoch    0/20 Batch 2/3 Cost: 5092.103516
Epoch    0/20 Batch 3/3 Cost: 836.946655
Epoch    1/20 Batch 1/3 Cost: 357.680664
Epoch    1/20 Batch 2/3 Cost: 133.807770
Epoch    1/20 Batch 3/3 Cost: 40.606392
Epoch    2/20 Batch 1/3 Cost: 7.806302
Epoch    2/20 Batch 2/3 Cost: 8.140214
Epoch    2/20 Batch 3/3 Cost: 0.375048
Epoch    3/20 Batch 1/3 Cost: 0.153911
Epoch    3/20 Batch 2/3 Cost: 2.094448
Epoch    3/20 Batch 3/3 Cost: 0.087249
Epoch    4/20 Batch 1/3 Cost: 0.076669
Epoch    4/20 Batch 2/3 Cost: 0.003561
Epoch    4/20 Batch 3/3 Cost: 3.377001
Epoch    5/20 Batch 1/3 Cost: 1.243739
Epoch    5/20 Batch 2/3 Cost: 0.529664
Epoch    5/20 Batch 3/3 Cost: 0.164940
Epoch    6/20 Batch 1/3 Cost: 1.458122
Epoch    6/20 Batch 2/3 Cost: 0.193437
Epoch    6/20 Batch 3/3 Cost: 0.085822
Epoch    7/20 Batch 1/3 Cost: 0.056428
Epoch    7/20 Batch 2/3 Cost: 1.665085
Epoch    7/20 Batch 3/3 Cost: 0.174672
Epoch    8/20 Batch 1/3 Cost: 1.514408
Epoch    8/

In [69]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[150.7941]], grad_fn=<AddmmBackward0>)
